version: 2.1 

 

jobs: 546584e

  build-and-test:  

    machine: 

      image: ubuntu-2004:202104-01 

        

    steps: 

      - checkout 

      - run: make deps 

      - run: make test       

workflows: 
adda
  basic:  

    jobs: 

      - build-and-test dad